  version: '3.8'
  services:
    list:
      build: ./books
      ports:
         - "8080:8080"
      networks:
        - listNetwork
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080/books || exit 1"]
        # test: ["CMD-SHELL", "curl -f https://localhost:8080/list/books || exit 1"]
        interval: 2s
        timeout: 5s
        start_period: 2s
        retries: 5

    curl:
      image: curlimages/curl
      depends_on:
        list:
          condition: service_healthy
      command: -L -v http://list:8080/list/books
      networks:
        - listNetwork
  networks:
    listNetwork:
      driver: bridge